[[rules]]
id = "wecode-internal-key"
description = "Détection des clés d'accès internes WeCode"
regex = '''WECODE-KEY-[A-Z0-9]{16}'''
secretGroup = 0

[allowlist]
description = "Ignorer le faux positif de la documentation par son empreinte unique"
fingerprints = [
    "e63c9aa1b4c9d91cb1b291bae20b2deec7bc8912:test_internal.py:wecode-internal-key:8"
]
